### ISSUE TITLE
sys-auth/fprintd-clients doesn't compile on OpenRC.

### ISSUE THREAD

**Issue by dnfm** [vowstar/vowstar-overlay#12]
The fprint stuff seems to be pretty heavily systemd-centric.

An attempt to compile fprintd-clients (a prereq for python-validity) gives:

```
Run-time dependency systemd found: NO (tried pkgconfig and cmake)

meson.build:88:0: ERROR: Dependency "systemd" not found, tried pkgconfig and cmake
```

It looks like a line in the meson.build file tries to guarantee a specific version of systemd without checking whether the option was set to libelogind or not.

Even after removing that line, other errors pop up about positinal arguments in data/meson.build because it's providing a positional argument of 'polkit_policy' in i18n.merge_file, when it is unnecessary.

Nevertheless, even after deleting the extraneous argument, compiling, and installing, attempting to fprintd-enroll returns:

```
list_devices failed: The name net.reactivated.Fprint was not provided by any .service files
```

validity-led-dance does work, so the validity module is seeing and can access the fingerprint reader; the issue seems to simply be a missing dbus service file.

**Comment by vowstar** [comment]
Sorry, my current computer has no fingerprint function, so it is difficult to verify this ebuild, if you are interested, you can directly submit a PR or fork a new ebuild.

**Comment by hyegeek** [comment]
It only needs a quick edit to compile on an openrc system, though I found a second issue that probably breaks it on both openrc and system as there is a change to meson that needs a second change to work.

What I did edit the meson file that fails on systemd and commented out most of the systemd stuff (there was one variable that was needed later that I left alone). This is probably not the best approach, but it allowed me to get it installed.

The second error is in a different meson file and is related to positional arguments. The line it complains about just needs the first argument removed.

With those two changes, I was able to ebuild path-to-ebuild compile to finish the compile and then ebuild ... install to install it.

When I get a chance in the next couple of days, I'll try to produce a patch.

**Comment by mimi0000oo** [comment]
Hey, any chance to get the fix for this? I'm struggling for a couple of days with it and nothing works so far.

**Comment by mimi0000oo** [comment]
I continued to do some research. I managed to get the fprintd-clients package to compile **without pam**. It seems though that python-validity cannot run on an openrc-system without some major modifications (as far as I can see from the code). I think, at this moment it is all a bit of a waste of time. I will also post the modified git repository on my profile if you want to struggle with this. 

Good luck!

**Comment by hyegeek** [comment]
The modification were pretty minor to get it to compile. My description above should give enough hints to make it work. I've get to get to creating a patch. This is all working on my laptop which is running openrc.

**Comment by vowstar** [comment]
Thanks!

**Comment by mimi0000oo** [comment]
> The modification were pretty minor to get it to compile. My description above should give enough hints to make it work. I've get to get to creating a patch. This is all working on my laptop which is running openrc.

Maybe you could figure out a patch for it all. It would be amazing! Although I got fprintd-clients working. It got me so far to the enroll part, as I could not get python-validity to run properly.

**Comment by hyegeek** [comment]
After finally getting around to trying to create a patch, I ran into an unexpected problem. sys-auth/fprintd-clients just compiled fine. All I needed to do was add a couple of dependancies that the ebuild didn't pull in.

What issue are you seeing with the latest ebuild?  On my machine, the ebuild date is from last January.

**Comment by mimi0000oo** [comment]
Well, fprintd-clients, python-validity and open-fprintd all compile fine, the problem on my system is that the python-validity service is needed in order to actually use fprintd-clients and without it it shows an error: `list_devices failed:`. The python-validity package compiles just fine, but it does not provide an openrc service, but a systemd one. I tried to convert it to openrc but to no succes.

Do you have a working python-validity service?

For refference: https://github.com/uunicorn/python-validity#error-situations

**Comment by hyegeek** [comment]
You just need to run the dbus-service and the open-fprintd progrosm. I created a a fingerprint.start file in /etc/local.d/ with the contents

#!/bin/bash
/usr/lib/python-validity/dbus-service &
/usr/lib/open-fprintd/open-fprintd &

**Comment by mimi0000oo** [comment]
Well, it does not work for me. I tried running manually, recompiling everything, putting the script in /etc/local.d/. 

Here is the error:
`/usr/lib/open-fprintd/open-fprintd:25: PyGIDeprecationWarning: GObject.MainLoop is deprecated; use GLib.MainLoop instead
  GObject.MainLoop().run()
/usr/lib/python-validity/dbus-service:33: PyGIDeprecationWarning: Since version 3.11, calling threads_init is no longer needed. See: https://wiki.gnome.org/PyGObject/Threading
  GLib.threads_init()
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/handlers.py", line 987, in emit
    self.socket.send(msg)
OSError: [Errno 9] Bad file descriptor

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/handlers.py", line 908, in _connect_unixsocket
    self.socket.connect(address)
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/handlers.py", line 990, in emit
    self._connect_unixsocket(self.address)
  File "/usr/lib/python3.10/logging/handlers.py", line 919, in _connect_unixsocket
    self.socket.connect(address)
FileNotFoundError: [Errno 2] No such file or directory
Call stack:
  File "/usr/lib/python-validity/dbus-service", line 307, in <module>
    main()
  File "/usr/lib/python-validity/dbus-service", line 264, in main
    init.open()
  File "/usr/lib/python3.10/site-packages/validitysensor/init.py", line 48, in open
    open_common()
  File "/usr/lib/python3.10/site-packages/validitysensor/init.py", line 29, in open_common
    init_flash()
  File "/usr/lib/python3.10/site-packages/validitysensor/init_flash.py", line 116, in init_flash
    logging.info('Flash has %d partitions.' % len(info.partitions))
Message: 'Flash has 5 partitions.'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/handlers.py", line 987, in emit
    self.socket.send(msg)
OSError: [Errno 9] Bad file descriptor

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/handlers.py", line 908, in _connect_unixsocket
    self.socket.connect(address)
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/handlers.py", line 990, in emit
    self._connect_unixsocket(self.address)
  File "/usr/lib/python3.10/logging/handlers.py", line 919, in _connect_unixsocket
    self.socket.connect(address)
FileNotFoundError: [Errno 2] No such file or directory
Call stack:
  File "/usr/lib/python-validity/dbus-service", line 307, in <module>
    main()
  File "/usr/lib/python-validity/dbus-service", line 264, in main
    init.open()
  File "/usr/lib/python3.10/site-packages/validitysensor/init.py", line 48, in open
    open_common()
  File "/usr/lib/python3.10/site-packages/validitysensor/init.py", line 30, in open_common
    usb.send_init()
  File "/usr/lib/python3.10/site-packages/validitysensor/usb.py", line 93, in send_init
    logging.info('Clean slate')
Message: 'Clean slate'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/handlers.py", line 987, in emit
    self.socket.send(msg)
OSError: [Errno 9] Bad file descriptor

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/handlers.py", line 908, in _connect_unixsocket
    self.socket.connect(address)
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/handlers.py", line 990, in emit
    self._connect_unixsocket(self.address)
  File "/usr/lib/python3.10/logging/handlers.py", line 919, in _connect_unixsocket
    self.socket.connect(address)
FileNotFoundError: [Errno 2] No such file or directory
Call stack:
  File "/usr/lib/python-validity/dbus-service", line 307, in <module>
    main()
  File "/usr/lib/python-validity/dbus-service", line 264, in main
    init.open()
  File "/usr/lib/python3.10/site-packages/validitysensor/init.py", line 48, in open
    open_common()
  File "/usr/lib/python3.10/site-packages/validitysensor/init.py", line 33, in open_common
    upload_fwext()
  File "/usr/lib/python3.10/site-packages/validitysensor/upload_fwext.py", line 30, in upload_fwext
    logging.info('No firmware detected. Uploading...')
Message: 'No firmware detected. Uploading...'
Arguments: ()
Traceback (most recent call last):
  File "/usr/lib/python-validity/dbus-service", line 307, in <module>
    main()
  File "/usr/lib/python-validity/dbus-service", line 264, in main
    init.open()
  File "/usr/lib/python3.10/site-packages/validitysensor/init.py", line 48, in open
    open_common()
  File "/usr/lib/python3.10/site-packages/validitysensor/init.py", line 33, in open_common
    upload_fwext()
  File "/usr/lib/python3.10/site-packages/validitysensor/upload_fwext.py", line 48, in upload_fwext
    with open(fw_path, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/share/python-validity/6_07f_lenovo_mis_qm.xpfwext'`

**Comment by hyegeek** [comment]
That looks like a firmware issue. Do you have the firmware for your reader installed on your machine?

**Comment by mimi0000oo** [comment]
> That looks like a firmware issue. Do you have the firmware for your reader installed on your machine?

I tought about that and I can't find anything about firmware on the gentoo wiki. As far as I can see it only shows how to install & use fprintd. How should install it?

**Comment by hyegeek** [comment]
Depends on the type of the fingerprint reader. I assume you have the linux-firmware package installed. If not, start there.

What type of reader is it? Do a google search for that reader and firmware and see if there is a package for it. If not, see if you can download it manually.

**Comment by mimi0000oo** [comment]
06cb:009a Synaptics, Inc. Metallica MIS Touch Fingerprint Reader
The "most common" T480 fingerprint reader.

**Comment by hyegeek** [comment]
That's the reader I'm using, so it should work. I don't remember where I found the firmware, but you should have error messages in your log files complaining about missing firmware. You should be able to do a google search for the missing files(s).

**Comment by hyegeek** [comment]
https://github.com/uunicorn/python-validity

Looks like you should run the command validity-sensors-firmware

**Comment by mimi0000oo** [comment]
Well, did all of the stuff there. For now This is the log:
`
/usr/lib/open-fprintd/open-fprintd:25: PyGIDeprecationWarning: GObject.MainLoop is deprecated; use GLib.MainLoop instead
  GObject.MainLoop().run()
/usr/lib/python-validity/dbus-service:33: PyGIDeprecationWarning: Since version 3.11, calling threads_init is no longer needed. See: https://wiki.gnome.org/PyGObject/Threading
  GLib.threads_init()
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/handlers.py", line 987, in emit
    self.socket.send(msg)
OSError: [Errno 9] Bad file descriptor

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/handlers.py", line 908, in _connect_unixsocket
    self.socket.connect(address)
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/handlers.py", line 990, in emit
    self._connect_unixsocket(self.address)
  File "/usr/lib/python3.10/logging/handlers.py", line 919, in _connect_unixsocket
    self.socket.connect(address)
FileNotFoundError: [Errno 2] No such file or directory
Call stack:
  File "/usr/lib/python-validity/dbus-service", line 307, in <module>
    main()
  File "/usr/lib/python-validity/dbus-service", line 264, in main
    init.open()
  File "/usr/lib/python3.10/site-packages/validitysensor/init.py", line 48, in open
    open_common()
  File "/usr/lib/python3.10/site-packages/validitysensor/init.py", line 29, in open_common
    init_flash()
  File "/usr/lib/python3.10/site-packages/validitysensor/init_flash.py", line 119, in init_flash
    logging.info('Flash was not initialized yet. Formatting...')
Message: 'Flash was not initialized yet. Formatting...'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/handlers.py", line 987, in emit
    self.socket.send(msg)
OSError: [Errno 9] Bad file descriptor

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/handlers.py", line 908, in _connect_unixsocket
    self.socket.connect(address)
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/handlers.py", line 990, in emit
    self._connect_unixsocket(self.address)
  File "/usr/lib/python3.10/logging/handlers.py", line 919, in _connect_unixsocket
    self.socket.connect(address)
FileNotFoundError: [Errno 2] No such file or directory
Call stack:
  File "/usr/lib/python-validity/dbus-service", line 307, in <module>
    main()
  File "/usr/lib/python-validity/dbus-service", line 264, in main
    init.open()
  File "/usr/lib/python3.10/site-packages/validitysensor/init.py", line 48, in open
    open_common()
  File "/usr/lib/python3.10/site-packages/validitysensor/init.py", line 29, in open_common
    init_flash()
  File "/usr/lib/python3.10/site-packages/validitysensor/init_flash.py", line 128, in init_flash
    partition_flash(info, flash_layout_hardcoded, client_public)
  File "/usr/lib/python3.10/site-packages/validitysensor/init_flash.py", line 94, in partition_flash
    logging.info('Detected Flash IC: %s, %d bytes' % (info.ic.name, info.ic.size))
Message: 'Detected Flash IC: W25Q80B, 1048576 bytes'
`

It seams that there is a very log bug thread for this exact model, which I am not entierly sure what to do with.
EDIT: https://github.com/uunicorn/python-validity/issues/3

**Comment by hyegeek** [comment]
Since I never ran into any that, I don't think I can help futher. Did this machine boot and work under windows? If you can initialize it under windows, it might be able to continue to work under linux. 

Other than that, I guess your best bet is to try to make sense of that thread.

**Comment by mimi0000oo** [comment]
> 
Well, I never touched windows on this one, so I can't tell you if it works or not. I will try to find something on that thread.

Anyway, thank you for all your help. I got much further from what I expected today!
